services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=vector_nexus
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  worker:
    build:
      context: .
      dockerfile: Dockerfile.flask
    command: python worker.py
    environment:
      FLASK_ENV: development
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: vector_nexus
      REDIS_HOST: redis
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: backend.app:app
      FLASK_ENV: development
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: vector_nexus
      REDIS_HOST: redis
    command: python -m flask run --host=0.0.0.0
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      worker:
        condition: service_started

volumes:
  mongodb_data: {}
